name: Tag on merge
on:
  push:
    branches:
      - main
jobs:
  tag-on-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Is variable exported?
        run: |
          echo "${{ env.GITHUB_REF }}"
      - name: Tag on merge into main
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.GITHUB_REF }}
