name: Tag on merge
on:
  push:
    branches:
      - main
jobs:
  tag-on-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Tag on merge into main
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: zingmane
          WITH_V: false
          CUSTOM_TAG: ${{ env.GITHUB_REF_NAME }}
          VERBOSE: true
